server:
  port: 9271

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  # 配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/store?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  mvc:
    path match:
      matching-strategy: ant-path-matcher


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 扫描通用枚举包
  type-enums-package: com.rabbiter.hrm.enums
















